# Generated by Django 3.1.3 on 2021-10-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaymovieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaymovie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
